#Spring Boot configuration
spring.application.name=event-service

#flyway
flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true
fail-on-missing-locations=true

#JPA properties
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true

# Postgres hostname
postgres.hostname=localhost

# Kafka outbox topic
event.outbox.topic=event_canceled

# Logger configuration
logging.pattern.level="%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
logging.level.org.springframework=debug
logging.level.org.hibernate.stat=debug
logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

# Server configuration
server.port=8081
server.error.include-binding-errors=always
server.error.include-message=always